### ISSUE TITLE
Doc team

### ISSUE THREAD

**Issue by raix** [raix/push#44]
If you think this package needs more documentation:

Documentation is currently maintained in the `docs` folder and the main `README.md` - I take pull requests here.

If you think the wiki is a better place then join the team and help maintain this package :)

If you think theres an area that needs better docs, then add a comment here,

Todo:
* [ ] Add documentation for: `The "Push.appCollection" is empty` #24
* [ ] Document how to solve "unable to get local issuer certificate" #41
* [ ] Better documentation for how to play a sound #36
* [ ] Where should the files be stored #34
* [ ] No tokens in Push.appCollection, sample app for iOS #33 (+ #26)
* [ ] basic example question #28 (much like #33 but with metadata explained)

Kind regards Morten

**Comment by dennisharrison** [comment]
I'm not ignoring this issue :)  Need the time to do it properly is all.

**Comment by dennisharrison** [comment]
I just learned a LOT about APN certs and provisioning profiles.  Will update the wiki first and then just put a link to that in the ```README.md```

I also haven't seen anyone run into #41 when following the walkthrough.

For #36 I'm trying to work out sounds for Android and then can write something up for it.

For #28 Can you write up a quick with metadata example and I'll try to document based on that?

**Comment by raix** [comment]
sounds cool @dennisharrison :+1: 

Theres a `Push.setMetadata(data)` method that stores data on the `metadata` field in the appCollection - it's still a bit in flux - and input / ideas is welcome. The point about metadata was to allow the developer to add data to the appCollection and being able to push messages to users based on custom data.

There are some security concerns, one is limiting the amount of data allowed in metadata - we could limit nr. of fields and depth level / have the metadata object flattened.

For now theres not much security on updating metadata - we might want to add some allow/deny rules.
We should also investigate if we somehow can do semi token auth on the ddp line - again for validation in allow/deny rules.

**Comment by dennisharrison** [comment]
@raix Can you give me an example of what the dictionary sent to setMetadata would look like and what the use would be for a search using it?

I've been keeping track of that in payload metadata and doing the search using a per app customized findUser method - usually based on information kept in user.profile.  Metadata is to help with this?

**Comment by raix** [comment]
It could be user want to subscribe to some news, so adding channels to the metadata allows the server to send out news targeted the user. Eg.
```js
Push.setMetadata({
  // Only subscribe to foo and bar
  subscriptions: [ 'foo', 'bar']
})
```

Then have:
```js
  Push.send(
    // ...
    query: {
      metadata: {
        subscriptions: 'foo'
      }
    }
  );
```
*100% untested...*

**Comment by dennisharrison** [comment]
Oh!, on the client.  I don't know what I was thinking :)  I'll try it now.

**Comment by raix** [comment]
Ah, well I think you catch things I take for granted - Important stuff for documentation :)
